### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by Madara2k04** [KlausJackson/image#2]
she is not Thu, Cam Ly
About Kim Anh, i need more images to submit, because there are two girls in the image (recommend images which she has a pair of glasses)
And Hoa? I don't know to talk anything, because in the image which she does not have glasses i see quite similar and the image having is not.

**Comment by KlausJackson** [comment]
Check kim_anh_2.jpg.

**Comment by Madara2k04** [comment]
Oh she is not Kim Anh

**Comment by Madara2k04** [comment]
But, i think again that i do not need her facebook, although thank you very much
